name: labyrinth

on: [push]

jobs:
    web-client:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web-client
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Set up node
          uses: actions/setup-node@v1
          with:
            node-version: "12.x"
        - name: Install dependencies
          run: |
            npm ci
        - name: Lint
          run: |
            npm run lint
        - name: Run tests
          run: |
            npm run test:unit
        - name: Build web-client
          run: |
            npm run build
        - name: Archive web-client
          uses: actions/upload-artifact@v1
          with:
            name: webClient
            path: backend/static

    algolibs:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./algolibs
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Setup cmake
          uses: lukka/get-cmake@latest
        - name: Run cmake and build shared library
          env:
            COMPILER: gcc-8
          run: |
            mkdir builds
            cmake -S. -Bbuilds/shared -DCMAKE_CXX_COMPILER={COMPILER}
            cmake --build builds/shared
            mkdir -p ../backend/instance/lib/
            cp builds/shared/libexhsearch/libexhsearch.so ../backend/instance/lib/
        - name: Run tests
          run: |
            mkdir ../test-results
            cd builds/shared/test/
            ctest -V
            mv all_tests.xml ../../../../test-results/algolibs-results.xml
            cd ../../../
        - name: Archive shared library
          uses: actions/upload-artifact@v1
          with:
            name: sharedLib
            path: backend/instance/lib/

    backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        needs: [web-client, algolibs]
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r dev-requirements.txt
        - name: Lint
          run: |
            flake8 . --count --max-line-length=120 --max-complexity=10 --show-source --statistics
        - name: Restore web-client artifact
          uses: actions/download-artifact@v1
          with:
            name: webClient
            path: backend/static
        - name: Restore shared library artifact
          uses: actions/download-artifact@v1
          with:
            name: sharedLib
            path: backend/instance/lib/
        - name: Run tests
          run: |
            pytest . --junitxml=../test-results/backend-results.xml --cov=server --cov-report=xml:../test-results/backend-coverage.xml
        - name: Archive deployment
          uses: actions/upload-artifact@v2
          with:
            name: deployment
            path: |
              backend/instance
              backend/static
              backend/labyrinth
              backend/requirements.txt
              backend/labyrinth_main.py
