name: VueJS web-client

on [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build
    - run: npm test:unit
