name: VueJS web-client

on: [push]
defaults:
  run:
    working-directory: ./web-client

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        npm ci
    - name: Run tests
      run: |
        npm test:unit
    - name: Build the application
      run: |
        npm run build

